import { BlogPostBase } from "./types";

export const baseBlogPosts: BlogPostBase[] = [
  {
    postId: "eta-istoriya-pro-odnogo-cheloveka",
    publishedAt: "2016-05-16T10:08:00+03:00",
    author: "Anton Kolhonen",
    status: "publish",
    rubric: { slug: "rubric:orientation-toward-overcoming" },
    category: { slug: "category:overcoming" },
    keywords: [{ slug: "keyword:inner-tension" }],
    keywordsRaw: ["успех", "преодоление", "мотивация"],
    coverImage: {
      src: "/images/posts/maxresdefault.jpg",
      width: 1280,
      height: 720,
    },
    coverLayout: "landscape",
    contentFiles: {
      ru: "lib/blog/posts/eta-istoriya-pro-odnogo-cheloveka/ru.md",
      en: "lib/blog/posts/eta-istoriya-pro-odnogo-cheloveka/en.md",
      de: "lib/blog/posts/eta-istoriya-pro-odnogo-cheloveka/de.md",
      fi: "lib/blog/posts/eta-istoriya-pro-odnogo-cheloveka/fi.md",
      cn: "lib/blog/posts/eta-istoriya-pro-odnogo-cheloveka/cn.md",
    },
  },
  {
    postId: "blizost-i-nezavisemost",
    publishedAt: "2016-12-15T09:00:00+03:00",
    author: "Anton Kolhonen",
    status: "publish",
    rubric: { slug: "rubric:det-notes" },
    category: { slug: "category:relationships-ideas" },
    keywords: [{ slug: "keyword:ambivalence" }],
    keywordsRaw: [
      "близость и независимость",
      "продуктивная любовь",
      "уважение в отношениях",
    ],
    coverImage: {
      src: "/images/posts/closeness-vs-independence.webp",
      width: 604,
      height: 404,
    },
    coverLayout: "square",
    contentFiles: {
      ru: "lib/blog/posts/blizost-i-nezavisemost/ru.md",
      en: "lib/blog/posts/blizost-i-nezavisemost/en.md",
      de: "lib/blog/posts/blizost-i-nezavisemost/de.md",
      fi: "lib/blog/posts/blizost-i-nezavisemost/fi.md",
      cn: "lib/blog/posts/blizost-i-nezavisemost/cn.md",
    },
  },
  {
    postId: "vzaimopomoshch-kak-faktor-evolyutsii",
    publishedAt: "2017-11-04T09:00:00+03:00",
    author: "Anton Kolhonen",
    status: "publish",
    rubric: { slug: "rubric:det-notes" },
    category: { slug: "category:humanistic-principles" },
    keywords: [{ slug: "keyword:inner-tension" }],
    keywordsRaw: [
      "взаимопомощь",
      "социальная природа человека",
      "гуманистическая перспектива",
    ],
    coverImage: {
      src: "/images/posts/vzaimopomoshch-kak-faktor-evolyutsii.webp",
      width: 686,
      height: 457,
    },
    coverLayout: "landscape",
    contentFiles: {
      ru: "lib/blog/posts/vzaimopomoshch-kak-faktor-evolyutsii/ru.md",
      en: "lib/blog/posts/vzaimopomoshch-kak-faktor-evolyutsii/en.md",
      de: "lib/blog/posts/vzaimopomoshch-kak-faktor-evolyutsii/de.md",
      fi: "lib/blog/posts/vzaimopomoshch-kak-faktor-evolyutsii/fi.md",
      cn: "lib/blog/posts/vzaimopomoshch-kak-faktor-evolyutsii/cn.md",
    },
  },
  {
    postId: "multidistsiplinarnyi-podkhod",
    publishedAt: "2017-11-15T09:00:00+03:00",
    author: "Anton Kolhonen",
    status: "publish",
    rubric: { slug: "rubric:det-notes" },
    category: { slug: "category:humanistic-principles" },
    keywords: [{ slug: "keyword:inner-tension" }],
    keywordsRaw: [
      "мультидисциплинарный подход",
      "целостное развитие",
      "взаимосвязь сфер здоровья",
    ],
    coverImage: {
      src: "/images/posts/multidisciplinarnyj-podhod.webp",
      width: 1280,
      height: 720,
    },
    coverLayout: "landscape",
    contentFiles: {
      ru: "lib/blog/posts/multidistsiplinarnyi-podkhod/ru.md",
      en: "lib/blog/posts/multidistsiplinarnyi-podkhod/en.md",
      de: "lib/blog/posts/multidistsiplinarnyi-podkhod/de.md",
      fi: "lib/blog/posts/multidistsiplinarnyi-podkhod/fi.md",
      cn: "lib/blog/posts/multidistsiplinarnyi-podkhod/cn.md",
    },
  },
];
