import { BlogPostBase } from "./types";

export const baseBlogPosts: BlogPostBase[] = [
  {
    postId: "eta-istoriya-pro-odnogo-cheloveka",
    publishedAt: "2016-05-16T10:08:00+03:00",
    author: "Anton Kolhonen",
    status: "publish",
    rubric: { slug: "rubric:orientation-toward-overcoming" },
    category: { slug: "category:overcoming" },
    keywords: [{ slug: "keyword:existential-choice" }],
    keywordsRaw: ["успех", "преодоление", "мотивация"],
    coverImage: {
      src: "/images/posts/maxresdefault.jpg",
      width: 1280,
      height: 720,
      alt: "Эта история про одного человека",
    },
    contentFiles: {
      ru: "lib/blog/posts/eta-istoriya-pro-odnogo-cheloveka/ru.md",
      en: "lib/blog/posts/eta-istoriya-pro-odnogo-cheloveka/en.md",
      de: "lib/blog/posts/eta-istoriya-pro-odnogo-cheloveka/de.md",
      fi: "lib/blog/posts/eta-istoriya-pro-odnogo-cheloveka/fi.md",
      cn: "lib/blog/posts/eta-istoriya-pro-odnogo-cheloveka/cn.md",
    },
  },
  {
    postId: "sila-i-svet-haus-i-mrak",
    publishedAt: "2016-06-23T12:10:00+03:00",
    author: "Anton Kolhonen",
    status: "publish",
    rubric: { slug: "rubric:shadow-and-light" },
    category: { slug: "category:psychology" },
    keywords: [],
    keywordsRaw: [],
    coverImage: {
      src: "/images/posts/sila-i-svet-haus-i-mrak.jpg",
      width: 450,
      height: 454,
      alt: "Сила и свет, хаус и мрак",
    },
    contentFiles: {
      ru: "lib/blog/posts/sila-i-svet-haus-i-mrak/ru.md",
      en: "lib/blog/posts/sila-i-svet-haus-i-mrak/en.md",
      de: "lib/blog/posts/sila-i-svet-haus-i-mrak/de.md",
      fi: "lib/blog/posts/sila-i-svet-haus-i-mrak/fi.md",
      cn: "lib/blog/posts/sila-i-svet-haus-i-mrak/cn.md",
    },
  },
  {
    postId: "blizost-i-nezavisemost",
    publishedAt: "2016-12-15T09:00:00+03:00",
    author: "Anton Kolhonen",
    status: "publish",
    rubric: { slug: "rubric:personal-psychology" },
    category: { slug: "category:relationships-ideas" },
    keywords: [{ slug: "keyword:ambivalence" }],
    keywordsRaw: [
      "близость и независимость",
      "продуктивная любовь",
      "уважение в отношениях",
    ],
    coverImage: {
      src: "/images/posts/closeness-vs-independence.webp",
      width: 604,
      height: 404,
      alt: "Близость и независимость в отношениях",
    },
    contentFiles: {
      ru: "lib/blog/posts/blizost-i-nezavisemost/ru.md",
      en: "lib/blog/posts/blizost-i-nezavisemost/en.md",
      de: "lib/blog/posts/blizost-i-nezavisemost/de.md",
      fi: "lib/blog/posts/blizost-i-nezavisemost/fi.md",
      cn: "lib/blog/posts/blizost-i-nezavisemost/cn.md",
    },
  },
  {
    postId: "sposoben-li-chelovek-izmenitsya",
    publishedAt: "2017-05-01T09:00:00+03:00",
    author: "Anton Kolhonen",
    status: "publish",
    rubric: { slug: "rubric:personal-lesgaft-study-notes" },
    category: { slug: "category:patterns" },
    keywords: [{ slug: "keyword:inner-tension" }],
    keywordsRaw: [
      "личностные изменения",
      "внутренние конфликты",
      "влияние среды",
    ],
    coverImage: {
      src: "/images/posts/sposoben-li-chelovek-izmenitsya.webp",
      width: 1600,
      height: 1200,
      alt: "Способность человека меняться через осознание и среду",
    },
    contentFiles: {
      ru: "lib/blog/posts/sposoben-li-chelovek-izmenitsya/ru.md",
      en: "lib/blog/posts/sposoben-li-chelovek-izmenitsya/en.md",
      de: "lib/blog/posts/sposoben-li-chelovek-izmenitsya/de.md",
      fi: "lib/blog/posts/sposoben-li-chelovek-izmenitsya/fi.md",
      cn: "lib/blog/posts/sposoben-li-chelovek-izmenitsya/cn.md",
    },
  },
  {
    postId: "multidistsiplinarnyi-podkhod",
    publishedAt: "2017-11-15T09:00:00+03:00",
    author: "Anton Kolhonen",
    status: "publish",
    rubric: { slug: "rubric:personal-psychology" },
    rubrics: [
      { slug: "rubric:personal-psychology" },
      { slug: "rubric:personal-health-practices" },
      { slug: "rubric:personal-training" },
    ],
    category: { slug: "category:humanistic-principles" },
    keywords: [{ slug: "keyword:inner-tension" }],
    keywordsRaw: [
      "мультидисциплинарный подход",
      "целостное развитие",
      "взаимосвязь сфер здоровья",
    ],
    coverImage: {
      src: "/images/posts/multidisciplinarnyj-podhod.webp",
      width: 1280,
      height: 720,
      alt: "Мультидисциплинарный подход",
    },
    contentFiles: {
      ru: "lib/blog/posts/multidistsiplinarnyi-podkhod/ru.md",
      en: "lib/blog/posts/multidistsiplinarnyi-podkhod/en.md",
      de: "lib/blog/posts/multidistsiplinarnyi-podkhod/de.md",
      fi: "lib/blog/posts/multidistsiplinarnyi-podkhod/fi.md",
      cn: "lib/blog/posts/multidistsiplinarnyi-podkhod/cn.md",
    },
  },
];
